---

name: Regenerate badges
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      name:
        description: 'Manually launched'


jobs:
  regenerate-badges:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Generate badges
        run: |
          pwd
          cd badges
          wget https://github.com/thibaultserti/badges/releases/download/0.1.0/badges -O badges
          chmod +x badges
          ./badges --website cryptohack    --username thibaultserti  --theme dark
          ./badges --website rootme        --username Thibault-Serti --theme dark
          ./badges --website newbiecontest --username 85319          --theme light
          wget https://projecteuler.net/profile/alvin666.png -O projecteuler.png
          wget https://tryhackme-badges.s3.amazonaws.com/thibaultserti.png -0 tryhackme.png
          wget http://www.hackthebox.eu/badge/image/384113 -o hackthebox.eu -0 hachthebox.png
      - name: Add badges and commit
        uses: EndBug/add-and-commit@v7
        with:
          add: 'badges/cryptohack.png badges/rootme.png badges/newbiecontest.png badges/projecteuler.png badges/tryhackme.png badges/hackthebox.png'
          message: 'Regenerate badges (Github actions)'
