---
name: 📊 Github activity metrics
on:
  # 🌏 Schedule updates
  schedule:
  - cron: "0 0 * * 1"
  # 💡 The following line lets you run workflow manually from the action tab!
  workflow_dispatch:
    inputs:
      name:
        description: 'Manually launched'

jobs:
  achievements:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.33
        with:
          filename: achievements.svg
          token: ${{ secrets.METRICS_SECRET }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: thibaultserti
          base: achievements
          plugin_achievements: yes
          plugin_achievements_threshold: B      # Display achievements with rank B or higher
          plugin_achievements_secrets: yes      # Display unlocked secrets achievements
          plugin_achievements_display: compact  # Use compact display
          plugin_achievements_limit: 0          # Display all unlocked achievements (no limit)
          plugins_errors_fatal: yes

  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.33
        with:
          filename: header.svg
          # You'll need to setup a personal token in your secrets.
          token: ${{ secrets.METRICS_SECRET }}
          # GITHUB_TOKEN is a special auto-generated token used for commits
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: thibaultserti
          template: classic
          base: header
          config_timezone: ${{ vars.USER_TIMEZONE }}
          plugins_errors_fatal: yes

  lines:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.33
        with:
          filename: lines-of-code.svg
          token: ${{ secrets.METRICS_SECRET }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "repositories"
          plugin_lines: yes
          plugins_errors_fatal: yes

  acti_comm:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.33
        with:
          filename: acti_comm.svg
          # You'll need to setup a personal token in your secrets.
          token: ${{ secrets.METRICS_SECRET }}
          # GITHUB_TOKEN is a special auto-generated token used for commits
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: thibaultserti
          template: classic
          base: activity, community
          config_timezone: ${{ vars.USER_TIMEZONE }}
          plugins_errors_fatal: yes

  iso_calender:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.33
        with:
          filename: iso_calender.svg
          # You'll need to setup a personal token in your secrets.
          token: ${{ secrets.METRICS_SECRET }}
          # GITHUB_TOKEN is a special auto-generated token used for commits
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: thibaultserti
          template: classic
          base: ""
          config_timezone: ${{ vars.USER_TIMEZONE }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugins_errors_fatal: yes


  habits:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.33
        with:
          filename: github-habits.svg
          token: ${{ secrets.METRICS_SECRET }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_timezone: ${{ vars.USER_TIMEZONE }} # Set timezone
          user: thibaultserti
          base: ""
          template: classic
          plugin_habits: yes
          plugin_habits_from: 200       # Use 200 events to compute habits
          plugin_habits_days: 14        # Keep only events from last 14 days
          plugin_habits_charts: yes     # Display charts section
          plugin_habits_trim: yes       # Trim unused hours on daily chart
          plugins_errors_fatal: yes

  issue_pr_lang:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.33
        with:
          filename: issue_pr_lang.svg
          # You'll need to setup a personal token in your secrets.
          token: ${{ secrets.METRICS_SECRET }}
          # GITHUB_TOKEN is a special auto-generated token used for commits
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: thibaultserti
          template: classic
          base: ""
          config_timezone: ${{ vars.USER_TIMEZONE }}
          plugin_followup: yes
          plugin_languages: yes
          plugins_errors_fatal: yes

  repositories:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.33
        with:
          filename: repositories.svg
          # You'll need to setup a personal token in your secrets.
          token: ${{ secrets.METRICS_SECRET }}
          # GITHUB_TOKEN is a special auto-generated token used for commits
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: thibaultserti
          template: classic
          base: repositories
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          plugins_errors_fatal: yes
